### ISSUE TITLE
Erro na execução do projeto

### ISSUE THREAD

**Issue by mateusfg7** [robotica-desafios/shop-react-native#1]
quando executo o projeto aparesse alguns erros:

faltando 'name' ou 'slug':
![image](https://user-images.githubusercontent.com/40613276/83406256-a2f41e80-a3e4-11ea-8332-f3fabff02bf9.png)

faltando 'version':
![image](https://user-images.githubusercontent.com/40613276/83406480-1b5adf80-a3e5-11ea-9b0f-9eec8cba882b.png)

**Comment by marcoshenrique-dev** [comment]
Opa Matheus! Bom dia você criou o projeto como o mesmo nome que o meu? Provavelmente você criou um novo projeto e copiou as pastas ou fez um novo package.json, se puder mande a foto da estrutura de pasta no seu editor de código :)

**Comment by mateusfg7** [comment]
na verdade eu fiz um fork do projeto, executei `yarn install` depois `yarn start`
![image](https://user-images.githubusercontent.com/40613276/83407339-e8b1e680-a3e6-11ea-950e-d6127b3985cd.png)
a estrutura se mantem a mesma.
pelo que percebi era no package.json mesmo.
quando adicionei o 'name' e 'version', o problema se resolveu.
fiz um pull request com minhas alterações, nesse pull request #2 há tambem algumas mudanças no readme, coloquei uma descrição, caso vc goste :smile:

**Comment by marcoshenrique-dev** [comment]
Muito Obrigado! :)

**Comment by marcoshenrique-dev** [comment]
Coloquei seus updates na master do projeto ;)
